### PR TITLE
Use $USER instead of $SCREEN_NAME when looking for minecraft PID

### PR DESCRIPTION
**Pull request by orospakr**
The script was assuming that $SCREEN_NAME was your username.  Thus, if they didn't match, the script would fail and spit out a ps usage message.

### CODE REVIEW

**Comment by endofzero** [comment]
Shit... i fucked up on the pull request... I wasn't looking at it correctly... 2.5 has your changes though. Next time I will do a proper pull.

**Comment by endofzero** [comment]
This change is causing issues with cron jobs, throwing the error:

ERROR: User name does not exist.

Do you have any idea on how to get around that?

**Comment by orospakr** [comment]
Oh, shoot. I was afraid of that.

Perhaps using `whoami` would be better?

**Comment by endofzero** [comment]
Maybe, but It might return the same results, I'll have to test it

I added this line for testing: echo "$0 ran at $(date) as user $USER: \$PATH == $PATH"

What is returns when you are running the script logged in as the user 'minecraft'
/home/minecraft/minecraft.sh ran at Mon Apr 11 21:44:05 MDT 2011 as user minecraft: $PATH == /home/minecraft/bin:/usr/local/bin:/usr/bin:/bin:/usr/games

What is returned by the cron output (cron was added via 'crontab -e' while signed in as the user 'minecraft'):
/home/minecraft/minecraft.sh ran at Mon Apr 11 08:25:02 MDT 2011 as user : $PATH ==/usr/local/bin:/usr/bin:/bin:/usr/local/lib

**Comment by endofzero** [comment]
whoami works like a charm... it's been updated... Can you test that out and let me know if that works for you?

**Pull request closed without merging**
